import type { NextPage } from 'next';
import Head from 'next/head';
import TopNav from '../../components/topNav';
import styles from './styles.module.css';
import Sidebar from '../../components/sidebar';

interface props {
  children: React.ReactNode;
}

const FormsAdminLayout: NextPage<props> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Mint Forms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className={styles.container}>
        <div className={styles.fakeMenu}></div>
        <div className={styles.rightSide}>
          <TopNav />
          <div className={styles.content}>{children}</div>
        </div>
      </div>
    </div>
  );
};

export default FormsAdminLayout;
